name: PR Update

on:
  pull_request:
  workflow_dispatch:

env:
  pr_id: ${{ github.event.number }}

concurrency:
  group: pr-update-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  setup:
    name: NPM install & cache

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.node_version }}

      - name: node_modules cache
        id: node-modules-cache
        uses: actions/cache@v3
        env:
          cache_name: node-modules-npm
          cache_key: ${{ vars.node_version }}-${{ hashFiles('package-lock.json') }}
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ env.cache_name }}-${{ env.cache_key }}
          restore-keys: ${{ runner.os }}-${{ env.cache_name }}-

      - name: NPM install
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci

  lint:
    name: Linters

    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 50

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.node_version }}

      - name: Restore node_modules from cache
        uses: actions/cache@v3
        env:
          cache_name: node-modules-npm
          cache_key: ${{ vars.node_version }}-${{ hashFiles('package-lock.json') }}
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ env.cache_name }}-${{ env.cache_key }}

      - name: Check the commit message
        run: npx --no -- commitlint --from HEAD~${{ github.event.pull_request.commits }}

      - name: Lint the code
        run: npm run lint

  build:
    name: Build packages

    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.node_version }}

      - name: Restore node_modules from cache
        uses: actions/cache@v3
        env:
          cache_name: node-modules-npm
          cache_key: ${{ vars.node_version }}-${{ hashFiles('package-lock.json') }}
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ env.cache_name }}-${{ env.cache_key }}

      - name: Build packages
        run: npm run build -ws

  test:
    name: Unit tests

    runs-on: ubuntu-latest

    needs: setup

    if: ${{ false }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.node_version }}

      - name: Restore node_modules from cache
        uses: actions/cache@v3
        env:
          cache_name: node-modules-npm
          cache_key: ${{ vars.node_version }}-${{ hashFiles('package-lock.json') }}
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ env.cache_name }}-${{ env.cache_key }}

      - name: Run unit tests
        run: npm test
